# -*- coding: utf-8 -*-
"""AI_Research_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pFCOOX89MQxCNor3MN8qaGoovOfA6bn
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-text-splitters
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q langchain-huggingface
!pip install -q google-generativeai
!pip install -q pypdf

import os

from langchain_community.document_loaders import (
    DirectoryLoader,
    PyPDFLoader
)

from langchain_text_splitters import (
    RecursiveCharacterTextSplitter
)

from langchain_huggingface import (
    HuggingFaceEmbeddings
)

from langchain_community.vectorstores import (
    Chroma
)

import google.generativeai as genai

os.makedirs("/content/pdfs", exist_ok=True)

print("Folder Created!")

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

import shutil

for file_name in uploaded.keys():
    shutil.move(
        f"/content/{file_name}",
        f"/content/pdfs/{file_name}"
    )

print("All PDFs moved successfully!")

print(os.listdir("/content/pdfs"))

loader = DirectoryLoader(
    "/content/pdfs",
    glob="*.pdf",
    loader_cls=PyPDFLoader
)

docs = loader.load()

print("Total Documents:", len(docs))

print(docs[0].metadata)

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(docs)

print("Total Chunks:", len(chunks))

print(chunks[0].metadata)

print("\n")

print(chunks[0].page_content[:300])

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding Model Loaded!")

vectordb = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="./multi_pdf_db"
)

print("Vector Database Created!")

retriever = vectordb.as_retriever(
    search_kwargs={"k": 4}
)

print("Retriever Ready!")

genai.configure(
    api_key="AQ.Ab8RN6LueXOq3mnqu2LkwT3KzTt6aTuIIIYIAgVWt0sXuI9FpA"
)

model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

print("Gemini Connected!")

def ask_rag(question):

    retrieved_docs = retriever.invoke(question)

    context = "\n\n".join(
        [doc.page_content for doc in retrieved_docs]
    )

    prompt = f"""
You are a helpful AI assistant.

Use ONLY the context below.

If the answer is not found in the context,
say:

I don't know based on the provided documents.

Context:
{context}

Question:
{question}

Answer:
"""

    response = model.generate_content(prompt)

    sources = []

    for doc in retrieved_docs:

        source = doc.metadata.get(
            "source",
            "Unknown"
        )

        page = doc.metadata.get(
            "page",
            0
        ) + 1

        sources.append(
            f"{source} (Page {page})"
        )

    sources = list(set(sources))

    return {
        "answer": response.text,
        "sources": sources
    }

result = ask_rag(
    "What is Machine Learning?"
)

print("Answer:\n")
print(result["answer"])

print("\nSources:\n")

for source in result["sources"]:
    print(source)

result = ask_rag(
    "What are the advantages of RAG?"
)

print("Answer:\n")
print(result["answer"])

print("\nSources:\n")

for source in result["sources"]:
    print(source)

result = ask_rag(
    "What is ChromaDB?"
)

print("Answer:\n")
print(result["answer"])

print("\nSources:\n")

for source in result["sources"]:
    print(source)

