# -*- coding: utf-8 -*-
"""AI_Research_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pFCOOX89MQxCNor3MN8qaGoovOfA6bn
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-text-splitters
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q langchain-ollama

!pip uninstall -y langchain langchain-core langchain-community langsmith langchain-text-splitters langchain-ollama

!pip install -q \
langchain==0.2.16 \
langchain-core==0.2.38 \
langchain-community==0.2.16 \
langchain-text-splitters==0.2.4 \
langsmith==0.1.147 \
chromadb \
sentence-transformers \
langchain-ollama

import langchain
import langchain_core

print("LangChain:", langchain.__version__)
print("LangChain Core:", langchain_core.__version__)

from google.colab import files

uploaded = files.upload()

from langchain_community.document_loaders import TextLoader

loader = TextLoader("company_policy.txt")
documents = loader.load()

print("Documents Loaded:", len(documents))
print(documents[0].page_content[:300])

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(documents)

print("Number of chunks:", len(chunks))
print("\nFirst Chunk:\n")
print(chunks[0].page_content)

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully!")

